In [1]:
from TimeSeries import TimeSeries
from TimeSeries import ArrayTimeSeries

In [2]:
s = TimeSeries([1,2,3,4])
s
print(s)



s = TimeSeries([1,2,3,4,5],[5,4,3,2,1])

s

len(s)

s[2]

s[4] = (3,6)

s

l = iter(s)

next(l)

next(l)

s = TimeSeries([1,2,3,4,6,7,4,4,3,3,4,5])

print(s)

l = s.itervalues()

next(l),next(l),next(l)

l2 = s.itertimes()
next(l2),next(l2),next(l2)

l3 = s.iteritems()
next(l3),next(l3),next(l3)

[(0, 1), (1, 2), (2, 3), (3, 4)]
[(0, 1), (1, 2), (2, 3), (3, 4), (4, 6) ... (11, 5)]


((0, 1), (1, 2), (2, 3))

In [3]:
#s = ArrayTimeSeries([1,2,3,4,5,6,7,8],[5,6,7,8,9,10,11,12])
s1 = ArrayTimeSeries([1,2,3,4],[5,6,7,8])
#s
print(s1)
print(type(s1._time_series[3]))

[[1 5], [2 6], [3 7], [4 8]]
<class 'numpy.ndarray'>


In [4]:
pair = (1,2)
index = 3
s1._time_series[index] = pair
s1._time_series

array([[1, 5],
       [2, 6],
       [3, 7],
       [1, 2]])

In [5]:
#type(s._time_series)
s1._time_series
#print(s1._time_series)

array([[1, 5],
       [2, 6],
       [3, 7],
       [1, 2]])

In [6]:
len(s1)

4

In [7]:
s1[2]

array([3, 7])

In [8]:
s1[3] = (3,6)
type(s1)
print(s1)
#s1._time_series

[[1 5], [2 6], [3 7], [3 6]]


In [9]:
l = iter(s1)
next(l),next(l)

(5, 6)

In [10]:
s = TimeSeries([1,2,3,4,6,7,4,4,3,3,4,5])
print(s)

[(0, 1), (1, 2), (2, 3), (3, 4), (4, 6) ... (11, 5)]


In [11]:
l = s1.itervalues()
next(l),next(l),next(l)

(5, 6, 7)

In [12]:
l2 = s1.itertimes()
next(l2),next(l2),next(l2)

(1, 2, 3)

In [13]:
l3 = s1.iteritems()
next(l3),next(l3),next(l3)

(array([1, 5]), array([2, 6]), array([3, 7]))

In [14]:
s1 = ArrayTimeSeries

In [15]:
a = TimeSeries([1,2,3], [0,5,10])
b = TimeSeries([100,-100], [2.5, 7.5])

In [19]:
a.interpolate([1])._time_series == TimeSeries([1.2], [1])._time_series

True

In [17]:
print (a.interpolate([1]))

[(1, 1.2)]


In [18]:
print(TimeSeries([1.2],[1]))

[(1, 1.2)]
